### PR TITLE
Introducing JPAStreamer CDI producer

### PR DESCRIPTION
**Pull request by tokazio**
Provide CDI integration with JPAStreamerProducer

I'v duplicated the integration/spring package and adapted it to 'cdi'

JPAStreamerProducer is @ApplicationScoped, maybe this scope isn't optimal ?!

see issue https://github.com/speedment/jpa-streamer/issues/193

### CODE REVIEW

**Comment by minborg** [comment]
Excellent with documentation and all. To be able to merge this PR, I need you to sign the CLA as per https://github.com/speedment/jpa-streamer/blob/develop/CONTRIBUTING.md

The easiest way is to just add the signed contributor license agreement directly in this PR under `/cla/`

Thanks! /Per

**Comment by minborg** [comment]
I have enabled build checks for this PR so there might be some issues there once the build completes.

**Comment by tokazio** [comment]
javax.enterprise is not visible when generating the javadoc, i've edited the module-info.java but i'm not sure (never worked with modules)

**Comment by minborg** [comment]
Are you able to provide a CLA?

**Comment by minborg** [comment]
Thanks for this contribution @tokazio !

**Pull request merged**
